source: .
destination:    ./_site
plugins:        ./_plugins
layouts:        ./_layouts
data_source:    ./_data
collections:    null

safe:   false
include:        [".htaccess"]
exclude:        []
keep_files:     [".git", ".svn"]
encoding:       "utf-8"
markdown_ext:   "markdown,mkdown,mkdn,mkd,md"

show_drafts:    null
limit_posts:    0
future: true
unpublished:    false

whitelist:      []
gems:   []

markdown:       kradown
highlighter:    rouge
lsi:    false
excerpt_separator:      "\n\n"
incremental:    false

detach: false
port:   4000
host:   127.0.0.1
baseurl: /jekyll_demo

permalink:      date
paginate_path:  /page:num
timezone:       null

quiet:  false
defaults:       []

rdiscount:
        extensions:     []

redcarpet:
        extensions:     []

kramdown:
        auto_ids:       true
        footnote_nr:    1
        entity_output:  as_char
        toc_levels:     1..6
        smart_quotes:   lsquo,rsquo,ldquo,rdquo
        enable_coderay: false

coderay:
        coderay_wrap:   div
        coderay_line_numbers:   inline
        coderay_line_number_start:      1
        coderay_tab_width:      4
        coderay_bold_every:     10
        coderay_css:    style
